version: '3'
services:
  db:
    container_name: "order_db"
    image: mariadb:latest
    ports:
      - 13306:3306
    restart: always
    environment:
     - MARIADB_DATABASE=orders
     - MARIADB_ROOT_PASSWORD=1234
